global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'booking-service'
    static_configs:
      - targets: ['booking-service:8081']

  - job_name: 'gateway'
    static_configs:
      - targets: ['gateway-service:8080']

  - job_name: 'analytics'
    static_configs:
      - targets: ['analytics-service:8082']
